-- Users: both parents and teachers, distinguished by role
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  phone VARCHAR(20) UNIQUE NOT NULL,
  password_hash VARCHAR(255), -- nullable if using OTP-only auth later
  full_name VARCHAR(150) NOT NULL,
  role VARCHAR(10) NOT NULL CHECK (role IN ('parent', 'teacher', 'admin')),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Subjects catalog
CREATE TABLE IF NOT EXISTS subjects (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL
);

-- Teacher profile (1-1 with users where role=teacher)
CREATE TABLE IF NOT EXISTS teacher_profiles (
  id SERIAL PRIMARY KEY,
  user_id INTEGER UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bio TEXT,
  photo_url VARCHAR(500),
  governorate VARCHAR(50) NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'suspended')),
  rejection_reason TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Which subjects a teacher teaches, and at what price
CREATE TABLE IF NOT EXISTS teacher_subjects (
  id SERIAL PRIMARY KEY,
  teacher_id INTEGER NOT NULL REFERENCES teacher_profiles(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  price_per_hour NUMERIC(6,2) NOT NULL,
  UNIQUE(teacher_id, subject_id)
);

-- Subscriptions (what makes a teacher visible/active)
CREATE TABLE IF NOT EXISTS subscriptions (
  id SERIAL PRIMARY KEY,
  teacher_id INTEGER NOT NULL REFERENCES teacher_profiles(id) ON DELETE CASCADE,
  plan VARCHAR(10) NOT NULL CHECK (plan IN ('monthly', 'yearly')),
  amount NUMERIC(8,2) NOT NULL,
  payment_status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')),
  payment_reference VARCHAR(255),
  starts_at TIMESTAMP,
  ends_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Ratings from parents
CREATE TABLE IF NOT EXISTS ratings (
  id SERIAL PRIMARY KEY,
  teacher_id INTEGER NOT NULL REFERENCES teacher_profiles(id) ON DELETE CASCADE,
  parent_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  score INTEGER NOT NULL CHECK (score BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(teacher_id, parent_id)
);

ALTER TABLE ratings ADD COLUMN IF NOT EXISTS guest_name VARCHAR(100); -- one rating per parent per teacher (can be updated)
);

-- Prepaid codes: generated by admin, redeemed by teachers instead of online payment
CREATE TABLE IF NOT EXISTS prepaid_codes (
  id SERIAL PRIMARY KEY,
  code VARCHAR(20) UNIQUE NOT NULL,
  plan VARCHAR(10) NOT NULL CHECK (plan IN ('monthly', 'yearly')),
  status VARCHAR(20) NOT NULL DEFAULT 'unused' CHECK (status IN ('unused', 'used', 'disabled')),
  used_by_teacher_id INTEGER REFERENCES teacher_profiles(id),
  used_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);
-- Areas (delegations/neighborhoods) each teacher covers within their governorate.
-- A teacher can tick multiple areas (e.g. a Tunis teacher covering Bardo + El Manar + El Menzah).
CREATE TABLE IF NOT EXISTS teacher_areas (
  id SERIAL PRIMARY KEY,
  teacher_id INTEGER NOT NULL REFERENCES teacher_profiles(id) ON DELETE CASCADE,
  area_name VARCHAR(100) NOT NULL,
  UNIQUE(teacher_id, area_name)
);
-- OTP verification codes for phone number verification
CREATE TABLE IF NOT EXISTS otp_codes (
  id SERIAL PRIMARY KEY,
  phone VARCHAR(20) NOT NULL,
  code VARCHAR(6) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_otp_codes_phone ON otp_codes(phone);

ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT FALSE;

ALTER TABLE teacher_profiles ADD COLUMN IF NOT EXISTS certificate_url VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(10) CHECK (gender IN ('male', 'female'));
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE teacher_profiles ADD COLUMN IF NOT EXISTS certificate_url VARCHAR(500);
CREATE INDEX IF NOT EXISTS idx_teacher_profiles_status ON teacher_profiles(status);
CREATE INDEX IF NOT EXISTS idx_teacher_areas_name ON teacher_areas(area_name);

CREATE INDEX IF NOT EXISTS idx_teacher_profiles_governorate ON teacher_profiles(governorate);
CREATE INDEX IF NOT EXISTS idx_teacher_subjects_subject ON teacher_subjects(subject_id);
CREATE INDEX IF NOT EXISTS idx_ratings_teacher ON ratings(teacher_id);

-- Seed subjects
INSERT INTO subjects (name) VALUES
  ('Mathématiques'), ('Physique'), ('Français'), ('Anglais'), ('Arabe'),
  ('Sciences Naturelles'), ('Informatique'), ('Philosophie'), ('Histoire-Géo'), ('Économie')
ON CONFLICT (name) DO NOTHING;
